### ISSUE TITLE
Error with module 'time'

### ISSUE THREAD

**Issue by almeida85** [ipudu/order#5]
Hi,

I get this error with try to execute `order` as `order water_traj.xyz -t oto -c 'OH2'`:

```
Traceback (most recent call last):
  File "/home/almeida/.local/bin/order", line 8, in <module>
    sys.exit(command_line_runner())
  File "/home/almeida/.local/lib/python3.8/site-packages/order/order.py", line 40, in command_line_runner
    t_start = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

I installed order as:

`pip3 install iorder`

... and I use python 3.8

Any help will be appreciated.

**Comment by gcassone-cnr** [comment]
Dear Pu Du, I'm encountering the same error as almeida85. Could you please comment on this? Thank you in advance, Giuseppe
